[build]
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

[functions."shoes"]
  timeout = 26

[functions."upload"]
  timeout = 20
