platform :ios, '16.0'
use_frameworks! :linkage => :static

target 'App' do
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'RevenueCat'
end
